### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by sam-writer** [HLTCHKUST/eigenvector-analysis#1]
Hi, I am not trying to pressure you, but I am curious about the timeline of posting this code.

**Comment by jshin49** [comment]
Hi, thanks for your interest, and sorry about the inconvenience.

We plan to push the code as soon as possible, but not sure of when exactly. 

But it wont be too long.

**Comment by ricvolpe** [comment]
Any updates on a release? The approach is very interesting

**Comment by bzhang42** [comment]
Bump on releasing the code!!

**Comment by jshin49** [comment]
Sorry for the long overdue delay. We finally released the code. The reason we were hesitating was that the code was only meant for analysis, but hope this helps anyway.
